# Generated by Django 4.1.5 on 2023-03-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_number', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('specialty', models.CharField(choices=[('generalist', 'Généraliste'), ('orthopedist', 'Orthopédiste'), ('dermatologist', 'Dermatologue'), ('ophthalmologist', 'Ophtalmologue'), ('neurologist', 'Neurologue'), ('cardiologist', 'Cardiologue'), ('rheumatologist', 'Rhumatologue'), ('ENT', 'ORL'), ('other', 'Autre')], max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.address')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('Code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prix', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('Datefin', models.DateField()),
                ('Datefab', models.DateField()),
                ('Stock', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Labratory',
            fields=[
                ('nom2', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email2', models.EmailField(max_length=250)),
                ('numero2', models.IntegerField()),
                ('URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('numSS', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nom1', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('start_time', models.TimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('treatment_duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.doctor')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.pharmacist')),
            ],
        ),
    ]
