# Generated by Django 4.1.5 on 2023-04-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='pharmacist',
            table='pharmacist',
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='persecription',
        ),
    ]
