# Generated by Django 4.1.5 on 2023-04-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0003_prescription_patient_alter_doctor_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
    ]
